### ISSUE TITLE
Thêm phản ứng của voi khi kéo ảnh đến vị trí của nó

### ISSUE THREAD

**Issue by bingo213** [bingo213/Phaser---CNPM#15]
- Nếu đúng hình được yêu cầu => hình ảnh vào trong bụng voi
- Nếu hình chưa đúng =>voi không ăn, hình ảnh trở về vị trí ban đầu

**Comment by dolong144** [comment]
có cách nào nhóm các khối giống nhau để viết code gọn lại khi mà các khối giống nhau thì có hiệu ứng giống nhau

**Comment by bingo213** [comment]
C có thể dùng .getName(string) của gameObject để đặt tên các hình giống nhau cùng một tên.

Tìm hiểu thêm tại link dưới:
https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.GameObject.html#setName__anchor

**Comment by bingo213** [comment]
Nhầm chút, dùng .setName(string) chứ không phải getName
